spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate

